### ISSUE TITLE
Can't use renderer without a UI image

### ISSUE THREAD

**Issue by m1keall1son** [unity3d-jp/MovieProxy#172]
I'm experiencing playback issues and editor crashes when trying to use the StreamingImageSequenceRenderer without a UI Image but with a target RenderTexture.  I set the streaming image sequence track binding to an object with the StreamingImageSequenceRenderer component and a custom RenderTexture asset.  I am using the Render Texture asset elsewhere.  

As it stands I now in order for it to work without issue, I have to have a child game object that has only a UI image/canvas/renderer on it which is unneeded when I'm only interested in the RenderTexture. 

I would also really love to access the internal texture directly via the scripting API.  Copying the image again to a RenderTexture is unnecessary for my purposes when there is already a Texture available hidden in the object.

**Comment by sindharta** [comment]
I created a simple test application to reproduce your error, but I can't seem to reproduce the playback issues and editor crashes you mentioned.
This is my test project, and the test scene is in Assets/Scenes/SampleScene
[SISTest.zip](https://github.com/unity3d-jp/StreamingImageSequence/files/5121239/SISTest.zip)

If you don't mind, could you please attach a sample project that demonstrates the error ? You can modify the sample project above as well. 
Also, please mention more details about your environment, like:
1. The Unity version you are using
2. The package version
3. OS (Windows/Mac)
4. etc

> I would also really love to access the internal texture directly via the scripting API. 

Thank you for the feedback. This is not difficult to add, and we'll consider adding this in the next version.

**Comment by m1keall1son** [comment]
Thank you for your swift response! Apologies for my lack of information. 

Unity version 2019.4
Package 0.3.2
Windows 10
i7-6700K CPU
GTX 980ti GPU
16GB RAM

Your example has shown me that I was mistaken about the root of my issue.  When the playable director is on the same object containing the Streaming image sequence renderer, I cannot play the timeline clip and the texture goes black.  See the attached project which i modified from the one you sent.  

[SISTest_revised.zip](https://github.com/unity3d-jp/StreamingImageSequence/files/5124227/SISTest_revised.zip)

**Comment by sindharta** [comment]
Thank you. I have confirmed the issue, and the fix is under way.
https://github.com/unity3d-jp/StreamingImageSequence/pull/177

**Comment by sindharta** [comment]
This has been fixed in version 0.3.3-preview.
Please feel free to open if you still manage to reproduce the bug.
