### ISSUE TITLE
Timing of RenderTexture copy for use with compute shaders

### ISSUE THREAD

**Issue by m1keall1son** [unity3d-jp/MovieProxy#175]
Hello again!  I have another issue perhaps you can advise on:

I'm using the streaming image sequence renderer as a method to replace the unity video player for providing an uncompressed texture sequence that is friendly with the Timeline -- which i'm loving!  I'm using the provided Texture stream as input to compute shaders that construct geometry in compute buffers and later in other draw calls use shaders to read the geometry from those compute buffers and texture them with the image sequence images. 

I'm running into a timing issues however.  The streaming image sequence renderer appears to copy the image sequence stream to the RenderTexture **after** all the compute dispatches are run in the frame but **before** the regular draw calls take place, meaning that the compute dispatches are using an old texture compared to the textures being used in the later draw calls.

The Unity video player does it's texture generation before the compute dispatches occur and the AVPro video player does it at the very top of the frame.  See the attached RenderDoc images as reference for when the textures are produced -- note the "Geo" indication is where the compute shaders i'm referring to are dispatched.

Unity 2019.4
img seq package 0.3.2
Windows 10
intel i7
GTX980ti 

![unity_video_timing (2)](https://user-images.githubusercontent.com/2464817/91204209-b8ba6c80-e6d1-11ea-8a40-410945df2f39.png)

![avpro_video_timing (2)](https://user-images.githubusercontent.com/2464817/91204218-bce68a00-e6d1-11ea-8193-5623cc6f2ba4.png)

![img_seq_timing (2)](https://user-images.githubusercontent.com/2464817/91204229-c2dc6b00-e6d1-11ea-95e4-79fbfee1beba.jpg)

I tried to move the Image Sequence Renderer's script execution order to happen before my script that dispatches the compute shaders, but it keeps disappearing from the list when I try to apply the change.

Any insight would be greatly appreciated!  Thanks.

**Comment by sindharta** [comment]
Referring to [Unity's order of execution](https://docs.unity3d.com/Manual/ExecutionOrder.html), Timeline processes frames  between `Update()` and `LateUpdate()`, and this is also the timing when the internal texture of StreamingImageSequence is updated.

Based on that, I would think that your compute shader dispatches needed to be executed in `LateUpdate()`. Have you tried this ?

**Comment by m1keall1son** [comment]
Thank you for the suggestion that appears to be working great!  thank you!
