### ISSUE TITLE
Mac Build fails to play image sequence

### ISSUE THREAD

**Issue by highlyinteractive** [unity3d-jp/MovieProxy#194]
I've tried this in 2019.4.10f1 and 2020.1.2f1 with 0.3.2 & 0.3.3 and Timeline 1.4.0 & 1.4.2

It works perfectly in the editor (aside from a UI error in 2020 that doesn't seem to affect anything)

But builds for PC & Mac do not render. No errors in the logs, and other Timeline elements are animating correctly.

I'm building for both platforms on Mac

**Comment by sindharta** [comment]
Thank you for the report. We'll look into it.

**Comment by sindharta** [comment]
Fixed in 0.5.1-preview
Please reopen this ticket if you still have any problem.
