### ISSUE TITLE
OSX build fails with compile errors

### ISSUE THREAD

**Issue by gangogames** [unity3d-jp/MovieProxy#362]
Hi there, 
While I was always able to build for WIn64, the OSX build fails with compile errors. At the top of the list is the following:
Library\PackageCache\com.unity.streaming-image-sequence@0.11.0-preview\Runtime\Scripts\Features\ImageFolderPlayableAsset.cs(4,13): error CS0234: The type or namespace name 'FilmInternalUtilities' does not exist in the namespace 'Unity' (are you missing an assembly reference?)
I added the filminternalutilities0.10.1-preview package in the packagemanager, but the errors still occur. I can successfully use the namespace Unity.FilmInternalUtilities in my classes though. Not sure why the build process still fails....

**Comment by sindharta** [comment]
Thank you for the repost. We'll take a look.

**Comment by sindharta** [comment]
Fixed in 0.12.0-preview. 
Please try it and let us know how it goes

**Comment by sindharta** [comment]
Closing the issue for now. Please feel free to reopen if necessary
