### ISSUE TITLE
Change image from the sequence on runtime

### ISSUE THREAD

**Issue by EricBatlle** [unity3d-jp/MovieProxy#404]
Hi, it is posible to change the images on the timeline-linked directory (sub-streamingassets) without the need of open again UnityEditor and re-made the entire playable director component? 
Maybe maintaining the same file names? 
I'm trying but seems like the track erases himself when detects no images on the folder :( 

I'm using Unity 2019.4.13f1 with Timeline Version 1.4.8

Thanks!

**Comment by sindharta** [comment]
When the Editor is open, the track will detect any changes in the image folder in order to refresh, but it should not erase itself.

Can you elaborate more about how you are changing the images, and what you are trying to do ?
Showing a video would be helpful.

**Comment by sindharta-tanuwijaya** [comment]
Closing due to non-activity.
Feel free to reopen when applicable
