### ISSUE TITLE
Texture Import Settings

### ISSUE THREAD

**Issue by twisty01** [unity3d-jp/MovieProxy#411]
It would be really useful to have texture import settings for loaded textures, for example for loading non-sRGB texture, different format (like R 16 bit), mipmaps, alpha etc.

**Comment by sindharta** [comment]
If the textures are under Assets (non-streaming assets), then StreamingImageSequence will use the result of Unity's texture import settings, which is the same as what you requested.

If the textures are in StreamingAssets, or outside Unity project, then the textures will always be loaded as RGBA32.

**Comment by sindharta** [comment]
Closing issue. Let me know if there are more questions related to this.
