### ISSUE TITLE
Problem with package on apple silicon

### ISSUE THREAD

**Issue by IJsLauw** [unity3d-jp/MovieProxy#413]
When running my project with a StreamingImageSequence on a new m1 mac the console get's flooded with these errors:

DllNotFoundException: StreamingImageSequence assembly:<unknown assembly> type:<unknown type> member:(null)
Unity.StreamingImageSequence.ImageLoader.GetImageDataInto (System.String fileName, System.Int32 imageType, Unity.StreamingImageSequence.ImageData& readResult) (at Library/PackageCache/com.unity.streaming-image-sequence@0.14.2-preview/Runtime/Scripts/Loader/ImageLoader.cs:53)
Unity.StreamingImageSequence.StreamingImageSequencePlayableAsset.QueueImageLoadTask (System.Int32 index, Unity.StreamingImageSequence.ImageData& imageData) (at Library/PackageCache/com.unity.streaming-image-sequence@0.14.2-preview/Runtime/Scripts/Features/SIS/StreamingImageSequencePlayableAsset.cs:334)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: StreamingImageSequence assembly:<unknown assembly> type:<unknown type> member:(null)

and Unexpected exception Burst.Compiler.IL.Aot.AotLinkerException: The native link step failed. Check previous exception in the log - linker command line : "Library/PackageCache/com.unity.burst@1.6.4/.Runtime/hostmac/lld -flavor darwin -arch arm64 -macosx_version_min 10.8 -sdk_version 10.9 -r -dylib -o "/Temp/Burst/burst-aotgx6gy3c3.b9o/5a68c0dab1dd7e0d5a2fe8870e47e24b.bundle" "Library/PackageCache/com.unity.burst@1.6.4/.Runtime/libs/burstRTL_m_arm64.a"

**Comment by sindharta** [comment]
Thank you for the feedback.
StreamingImageSequence is not supported on Mac Silicon yet.
This is in our roadmap, but it might take a bit more time to get this feature completed.

**Comment by sindharta** [comment]
Mac Silicon is partially supported starting from `0.15.0-preview`.

**Comment by sindharta** [comment]
Closing issue due to non-activity. 
 Please let me know if you have any problem
