### ISSUE TITLE
Windows Build fails to play image sequence

### ISSUE THREAD

**Issue by Tianpeng2333** [unity3d-jp/MovieProxy#463]
Hi there, my unity editor version is 2021.3.10f1, and the Streaming Image Sequence version is  0.15.3-preview, Timeline version is 1.6.4.
This package works perfectly in the editor, but builds for Windows don't render the image sequence.
btw: I've put my image into the `StreamingAssets` folder.

More Info:
- Image Type: PNG
- Image Number: 71
- Average Size of Image File: 7KB
- Image Resolution: 150px * 150px

**Comment by sindharta** [comment]
Just confirmed that Windows build works using the `StreamingImageSequence~` project in this repository.
Can you please attach your project here, or any sample that we can look to reproduce this ?

**Comment by Tianpeng2333** [comment]
> Just confirmed that Windows build works using the `StreamingImageSequence~` project in this repository. Can you please attach your project here, or any sample that we can look to reproduce this ?

I just tried to use the `StreamingImageSequence~` project in the repository to rebuild my project and it also doesn't work.
Here is a test project (development build for Windows Intel x64 can be found in the `/Bin` folder):  [https://peng-files.oss-cn-beijing.aliyuncs.com/StreamingImageSequenceTest.zip](https://peng-files.oss-cn-beijing.aliyuncs.com/StreamingImageSequenceTest.zip)

It works pretty well in the editor:
![EditorView](https://user-images.githubusercontent.com/39307070/192574716-02bf8d24-d2f7-4730-9aec-dad39d37cbf5.jpg)

But it doesn't work after compiling:
![GameView](https://user-images.githubusercontent.com/39307070/192574930-b318dd7a-0106-44ee-a06b-a76e7dd151ba.jpg)

**Comment by sindharta** [comment]
Your sample project works for me.
Perhaps the clip is too short that it finishes as soon as Unity starts.
To test this, try setting the animation extrapolation property to `Loop`.

![image](https://user-images.githubusercontent.com/7379311/192762565-5c6f3302-e76a-47e8-9e25-0a4e72abb30c.png)

**Comment by Tianpeng2333** [comment]
> Your sample project works for me. Perhaps the clip is too short that it finishes as soon as Unity starts. To test this, try setting the animation extrapolation property to `Loop`.
> 
> ![image](https://user-images.githubusercontent.com/7379311/192762565-5c6f3302-e76a-47e8-9e25-0a4e72abb30c.png)

I've changed the animation extrapolation property to `loop`, and the director component's wrap mode to `loop`. But it still can't play in the runtime.  
To make sure it's not a problem with Playable Director or Timeline, I added another audio source track to Timeline. In the editor both the sequence images and the audio play perfectly, but in the runtime only the audio is playing.
![image](https://user-images.githubusercontent.com/39307070/192815849-6d62e6c9-be7f-4d19-a4c3-6c1f3139ff62.png)

I'm using editor version `2021.3.10f1` instead of `2020.3.40f1` and I don't know if this will cause any problems.

**Comment by sindharta** [comment]
That is curious. 
I am also using 2021.3.10f1 (your project as it is).
Let me try in another machine.

**Comment by sindharta** [comment]
Just tested in another machine and it still works. 
Do you have any error logs ?
And can you try in another machine ?

https://user-images.githubusercontent.com/7379311/192968614-eddd7a58-70c7-45fc-aa8f-2e2f542a33d5.mp4

**Comment by Tianpeng2333** [comment]
I found the cause of the problem.
On my computer, my project directory contains Chinese characters. When I moved the compiled program to a directory consisting of only numbers and English letters, it worked fine.
I think the problem may be due to the support for UTF-8 encoding that causes the program to not read the Streaming Assets in the Chinese directory.
Thank you for your continued help!

**Comment by sindharta** [comment]
That is good info. 
Thank you for the feedback
