### ISSUE TITLE
not working in 2022.1.20f1/2022.1.23f1

### ISSUE THREAD

**Issue by jingpe** [unity3d-jp/MovieProxy#475]
not working in 2022.1 version. 

shows null exception error for uiimage

**Comment by sindharta** [comment]
Thank you for the report. We'll check this.

**Comment by sindharta** [comment]
This looks like a bug that occurs starting from Unity 2022.x.
I am currently in talks with the UI team about this, and unfortunately we can't avoid/fix this from the StreamingImageSequence side.
I'll post updates to this issue as we go along.

**Comment by sindharta-tanuwijaya** [comment]
Confirmed to be working on Unity 2022.3.38f1.
Please reopen this issue if the issue still persists.
