### ISSUE TITLE
building help? 

### ISSUE THREAD

**Issue by DrSouil** [unity3d-jp/MovieProxy#476]
build my own project from Unity Editor doesn't work, how could I use the plugin below to build my own Unity project?
https://github.com/unity3d-jp/StreamingImageSequence/blob/dev/Plugins~/Docs/en/BuildPlugins.md

**Comment by sindharta** [comment]
That document explains the steps required to build the plugins that exist under [Runtime/Plugins](https://github.com/unity3d-jp/StreamingImageSequence/tree/dev/Runtime/Plugins) folder, so you should not need to build the plugin by yourself unless you are trying to customize it.

If you are trying to build a Unity runtime project, then you should be able to just follow the [Publishing Builds documentation](https://docs.unity3d.com/Manual/PublishingBuilds.html), unless you are trying to do something else ?

**Comment by DrSouil** [comment]
Thank you for the replay. Yes I want to build a Unity runtime project to play sequential images. Does the sequential images have to be put in the StreamingAssets folder? If so, the images could not have other Fomat other than "RGBA 32 bit, no POT scaling"?

**Comment by DrSouil** [comment]
The reason I'm asking is because I need to use 16bit single channel Depth images extracted from Azure Kinect recordings to build VFX graph. Maybe there is another walk-around? Thanks.

**Comment by sindharta** [comment]
To use the images in Runtime build, StreamingImageSequence unfortunately has the limitations that you mentioned above at the moment.
See [folder tradeoffs](https://docs.unity3d.com/Packages/com.unity.streaming-image-sequence@0.15/manual/FeaturePlayingSequentialImages.html#folder-tradeoffs) documentation for more details.

> The reason I'm asking is because I need to use 16bit single channel Depth images extracted from Azure Kinect recordings to build VFX graph. Maybe there is another walk-around?

If you are not too concerned about depth accuracy, then I believe you should be able to sample one channel from the  RGBA images.

**Comment by DrSouil** [comment]
Thanks
