### ISSUE TITLE
Runtime modification of image folder location in StreamingImageSequencePlayableAsset

### ISSUE THREAD

**Issue by ylequilleuc** [unity3d-jp/MovieProxy#492]
Hi, 

In a timeline using a StreamingImageSequencePlayableAsset, is it possible to changed the binded folder at runtime ?

The usecase is :
    - Gameplay holds potential teams, for each a dedicated folder with images for the sequence
    - Use of a single timeline to display those image
    - The "potential team" can change each game

The folder.ImageSequence can be modified in the inspector but it does not seem possible at runtime. Am I missing something ?

Apologize if it's more a question than an issue. The issue would be API not available ?

**Comment by sindharta-tanuwijaya** [comment]
Hi, thank you for your comment. 
Unfortunately, we do not support changing the folder at runtime at the moment. 
We do have an internal API to do this: `StreamingImageSequencePlayableAsset.SetFolder` which is derived from `ImageFolderPlayableAsset` class.

You can try modifying the package and making the API public to see if it works for your case.
