### ISSUE TITLE
Enter play mode locks up PC

### ISSUE THREAD

**Issue by gekidoslair** [unity3d-jp/MovieProxy#64]
Just created a simple sample scene setup with a single image sequence track pointing to a worldspace UI Image. Everything working fine in edit mode, can scrub, see the sequence etc.

However, when I hit 'play' on the editor it literally locked up my PC and I had to do a hard-reboot.

On windows, Unity 2019.3f7, package version 0.1.3

**Comment by gekidoslair** [comment]
note: after rebooting the PC I tried to reproduce and it didn't happen so no idea what happened the first time? very strange.

**Comment by gekidoslair** [comment]
going to close as 'my computer did something strange'...doesn't seem to repro

**Comment by gekidoslair** [comment]
Have repro'd with a couple of projects now (and different users / pc's) so this is definitely a thing - ideas?

**Comment by sindharta** [comment]
This should have been fixed in version 0.1.4-preview.
Are you still having this issue ?

**Comment by gekidoslair** [comment]
Ah ok will dbl check!

Thanks!

**Comment by sindharta** [comment]
I am closing this issue.
Please reopen it if you still notice it happening in version 0.1.4-preview or later
