### ISSUE TITLE
package version 0.1.4 NUnit dependency in PreviewTextureFactory

### ISSUE THREAD

**Issue by gekidoslair** [unity3d-jp/MovieProxy#71]
Getting compile errors in PreviewTextureFactory if I don't have the Unity test framework package in my project:

D:\projects\com.unity.streaming-image-sequence\Editor\StreamingImageSequence\PreviewTextureFactory.cs(2,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)

Looks like there are some tests interspersed with the package code?

**Comment by fingerx** [comment]
download last build,unzip and using package manager load it

**Comment by sindharta** [comment]
Fixed in version 0.1.5-preview
